participants: 
  - el_type: geth
    el_image: ethereum/client-go:v1.14.3
    # cl_type: lighthouse
    cl_type: nimbus
    el_extra_params: ["--gcmode=archive"]
    # cl_image: sigp/lighthouse:v5.1.3
    # cl_image: sigp/lighthouse:v7.0.1
    # cl_image: sigp/lighthouse:v6.0.1
    count: 1
  - el_type: erigon
    el_image: erigontech/erigon:2.60.7
    cl_type: nimbus
    count: 1
  - el_type: besu
    el_image: hyperledger/besu:24.1.2
    cl_type: nimbus
    count: 1
  - el_type: nethermind
    el_image: nethermind/nethermind:1.26.0
    cl_type: nimbus
    count: 1
  - el_type: reth
    el_image: ghcr.io/paradigmxyz/reth:v1.0.0
    cl_type: nimbus
    count: 1

network_params:
  network: kurtosis
  network_id: "15"
  seconds_per_slot: 6
  electra_fork_epoch: 9999871
  fulu_fork_epoch: 9999872
  preset: "minimal"
  prefunded_accounts: '{"0xFE3B557E8Fb62b89F4916B721be55cEb828dBd73": {"balance": "10000ETH"},
    "0xE25583099BA105D9ec0A67f5Ae86D90e50036425": {"balance": "10000ETH"},
    "0x614561D2d143621E126e87831AEF287678B442b8": {"balance": "10000ETH"},
    "0xf93Ee4Cf8c6c40b329b0c0626F28333c132CF241": {"balance": "10000ETH"},
    "0x802dCbE1B1A97554B4F50DB5119E37E8e7336417": {"balance": "10000ETH"}}'
  # prefunded_accounts: '{"0xFE3B557E8Fb62b89F4916B721be55cEb828dBd73": {"balance": "10000ETH"}}'

wait_for_finalization: false
global_log_level: info
snooper_enabled: false
ethereum_metrics_exporter_enabled: false
parallel_keystore_generation: false
disable_peer_scoring: false
persistent: false
checkpoint_sync_enabled: false

  # additional_services:
  # - tx_fuzz
