participants: 
  - el_type: geth
    el_image: ethereum/client-go:v1.14.12
    cl_type: lighthouse
    cl_image: sigp/lighthouse:v6.0.1
    # remote_signer_type: web3signer
    # remote_signer_image: consensys/web3signer:latest
    count: 1
  - el_type: erigon
    el_image: erigontech/erigon:2.60.8
    cl_type: lighthouse
    cl_image: sigp/lighthouse:v6.0.1
    # remote_signer_type: web3signer
    # remote_signer_image: consensys/web3signer:latest
    count: 1
  - el_type: besu
    el_image: hyperledger/besu:24.12.0
    cl_type: lighthouse
    cl_image: sigp/lighthouse:v6.0.1
    # # remote_signer_type: web3signer
    # # remote_signer_image: consensys/web3signer:latest
    count: 1
  - el_type: nethermind
    el_image: nethermind/nethermind:1.29.1
    cl_type: lighthouse
    cl_image: sigp/lighthouse:v6.0.1
    # remote_signer_type: web3signer
    # remote_signer_image: consensys/web3signer:latest
    count: 1
  - el_type: reth
    el_image: ghcr.io/paradigmxyz/reth:v1.1.0
    cl_type: lighthouse
    cl_image: sigp/lighthouse:v6.0.1
    # remote_signer_type: web3signer
    # remote_signer_image: consensys/web3signer:latest
    count: 1

network_params:
  network: kurtosis
  network_id: "15"
  deposit_contract_address: "0x4242424242424242424242424242424242424242"
  seconds_per_slot: 6
  num_validator_keys_per_node: 64
  preregistered_validator_keys_mnemonic:
    "giant issue aisle success illegal bike spike
    question tent bar rely arctic volcano long crawl hungry vocal artwork sniff fantasy
    very lucky have athlete"
  preregistered_validator_count: 0
  genesis_delay: 20
  genesis_gaslimit: 30000000
  max_per_epoch_activation_churn_limit: 8
  churn_limit_quotient: 65536
  ejection_balance: 16000000000
  eth1_follow_distance: 2048
  min_validator_withdrawability_delay: 256
  shard_committee_period: 256
  capella_fork_epoch: 0
  deneb_fork_epoch: 0 
  #  deneb_fork_epoch: 10000000
  electra_fork_epoch: 100000000
  fulu_fork_epoch: 100000001
  network_sync_base_url: 
  data_column_sidecar_subnet_count: 128
  samples_per_slot: 8
  custody_requirement: 4
  max_blobs_per_block_electra: 9
  target_blobs_per_block_electra: 6
  # max_blobs_per_block_fulu: 12
  # target_blobs_per_block_fulu: 9
  preset: "minimal"
  # additional_preloaded_contracts: {}
  # additional_preloaded_contracts: {}
  devnet_repo: ethpandaops
  # # A number of prefunded accounts to be created
  # # Defaults to no prefunded accounts
  # # Example:
  # # prefunded_accounts: '{"0x25941dC771bB64514Fc8abBce970307Fb9d477e9": {"balance": "10ETH"}}'
  # # 10ETH to the account 0x25941dC771bB64514Fc8abBce970307Fb9d477e9
  # # To prefund multiple accounts, separate them with a comma
  # #
  # prefunded_accounts: '{"0x25941dC771bB64514Fc8abBce970307Fb9d477e9": {"balance": "10ETH"}, "0x4107be99052d895e3ee461C685b042Aa975ab5c0": {"balance": "1ETH"}}'
  # cast wallet address --private-key 8f2a55949038a9610f50fb23b5883af3b4ecb3c3bb792cbcefbd1542c692be63
  prefunded_accounts: '{"0xFE3B557E8Fb62b89F4916B721be55cEb828dBd73": {"balance": "10000ETH"}}'
  # Withdrawal type
  # Default to "0x00"
  withdrawal_type: "0x00"
  # Withdrawal address
  # Default to "0x8943545177806ED17B9F23F0a21ee5948eCaa776" - 0 address of mnemonic
  withdrawal_address: "0x8943545177806ED17B9F23F0a21ee5948eCaa776"
  # Validator balance
  # Default to 32 ETH
  validator_balance: 32

# additional_services:
  # - tx_fuzz
# tx_fuzz_params:
#   # TX Spammer docker image to use
#   # Defaults to the latest master image
#   image: "ethpandaops/tx-fuzz:master"
#   # A list of optional extra params that will be passed to the TX Spammer container for modifying its behaviour
#   tx_fuzz_extra_args: []

wait_for_finalization: false
global_log_level: info
snooper_enabled: false
ethereum_metrics_exporter_enabled: false
parallel_keystore_generation: false
disable_peer_scoring: false
persistent: false
apache_port: 40000
global_tolerations: []
global_node_selectors: {}
keymanager_enabled: false
checkpoint_sync_enabled: false

ethereum_genesis_generator_params:
  image: ethpandaops/ethereum-genesis-generator:4.1.11
port_publisher:
  nat_exit_ip: KURTOSIS_IP_ADDR_PLACEHOLDER
  el:
    enabled: false
    public_port_start: 32000
  cl:
    enabled: false
    public_port_start: 33000
  vc:
    enabled: false
    public_port_start: 34000
  remote_signer:
    enabled: false
    public_port_start: 35000
  additional_services:
    enabled: false
    public_port_start: 36000
